spring:
  application:
    name: lagou-service-autodeliver

server:
  port: 9898

  #注册服务到eureka集群
eureka:
  client:
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true #服务器实例中显示IP，而不是主机名，使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都是ip）
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@ #⾃定义实例名称显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress

