server:
  port: 8762 #Eureka server服务端⼝

spring:
  application:
    name: lagou-cloud-eureka-server # 应⽤名称，会在Eureka中作为服务的id标识（serviceId）

#eureka客户端配置（和server交互），Eureka 客户端也是一个Client
eureka:
  client:
    service-url: # 客户端与EurekaServer交互的地址，如果是集群，也需要写其它Server的地址
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka
    register-with-eureka: true
    fetch-registry: true


  instance:
    appname: LagouCloudEurekaServerB #当前eureka实例的主机名