server:
  port: 9002

  #注册服务到eureka集群
eureka:
  client:
    service-url: # eureka server的路径 ,把 eureka 集群中的所有 url 都填写了进来，也可以只写⼀台，因为各个 eureka server 可以同步注册表
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true #服务器实例中显示IP，而不是主机名，使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都是ip）
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    #⾃定义实例名称显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress

spring:
  application:
    name: lagou-cloud-gateway-server
  cloud:
    gateway:
      routes: # 路由可以有多个
        - id: service-autodeliver-router # 我们⾃定义的路由 ID，保持唯⼀,配置了⼀个 id 为 service-autodeliver-router 的路由规则，当向⽹关发起请求 http://localhost:9002/autodeliver/checkState/2195381 ，请求会被分发路由到对应的微服务上
          uri: lb://LAGOU-SERVICE-AUTODELIVER  #http://127.0.0.1:9899 # ⽬标服务地址 ⾃动投递微服务（部署多实例） 动态路由： uri配置的应该是⼀个服务名称，⽽不应该是⼀个具体的服务实例的地址
          # gateway⽹关从服务注册中⼼获取实例信息然后负载后路由
          predicates: #断⾔：路由条件， Predicate 接受⼀个输⼊参数，返回⼀个布尔值结果。该接⼝包含多种默 认⽅法来将 Predicate 组合成其他复杂的逻辑（⽐如：与，或，⾮）。
            - Path=/autodeliver/**
        - id: service-resume-router
          uri: lb://LAGOU-SERVICE-RESUME # http://127.0.0.1:8080 # ⽬标服务地址 http://localhost:9002/resume/openstate/1545132,http://127.0.0.1:8080/openstate/1545132
          predicates:
            - Path=/resume/**
#          filters:
#            - StripPrefix=1
